import { error } from '@sveltejs/kit';
import { readFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
import type { RequestHandler } from './$types';

// HERE = ui/src/routes/api/audio → ../../../../../data lives at <repo-root>/data
const HERE = dirname(fileURLToPath(import.meta.url));
const URL_MAP_PATH = resolve(HERE, '..', '..', '..', '..', '..', 'data', 'audio-fix', 'url-map.json');

function safeStatus(code: number): 400 | 401 | 403 | 404 | 429 | 500 | 502 | 503 | 504 {
	// @sveltejs/kit's error() requires a NumericRange literal; map to the closest known bucket.
	if (code === 401 || code === 403 || code === 404 || code === 429) return code;
	if (code === 502 || code === 503 || code === 504) return code;
	if (code >= 400 && code < 500) return 400;
	return 502;
}

const ALLOWED_HOSTS = /^(data\.opencouncil\.gr|townhalls-gr\.fra1\.digitaloceanspaces\.com|www\.soundhelix\.com|objects\.githubusercontent\.com|github\.com|raw\.githubusercontent\.com)$/;

// URL rewrite map from data/audio-fix/url-map.json (generated by scripts/audio-fix/03-upload.sh).
// Lazy-loaded once on first request; missing file is silently ignored.
let urlMap: Map<string, string> | null = null;
async function getUrlMap(): Promise<Map<string, string>> {
	if (urlMap !== null) return urlMap;
	urlMap = new Map();
	try {
		const text = await readFile(URL_MAP_PATH, 'utf8');
		const obj = JSON.parse(text) as Record<string, string>;
		for (const [k, v] of Object.entries(obj)) urlMap.set(k, v);
		if (urlMap.size) console.info(`[api/audio] loaded url-map with ${urlMap.size} entries`);
	} catch { /* file doesn't exist yet — map stays empty */ }
	return urlMap;
}

export const GET: RequestHandler = async ({ url, request, fetch }) => {
	const target = url.searchParams.get('u');
	if (!target) throw error(400, 'missing u');

	let parsed: URL;
	try { parsed = new URL(target); } catch { throw error(400, 'bad url'); }

	if (parsed.protocol !== 'https:' || !ALLOWED_HOSTS.test(parsed.hostname)) {
		throw error(400, 'host not allowed');
	}

	// Apply URL rewrite map if a fixed version exists.
	const map = await getUrlMap();
	const mapped = map.get(target);
	if (mapped) {
		console.info('[api/audio] url-map hit', { original: target, mapped });
		try { parsed = new URL(mapped); } catch { throw error(500, 'bad mapped url'); }
		if (!ALLOWED_HOSTS.test(parsed.hostname)) throw error(500, 'mapped host not allowed');
	}

	const upstreamHeaders: Record<string, string> = {};
	const range = request.headers.get('range');
	if (range) upstreamHeaders['range'] = range;

	const upstream = await fetch(parsed.toString(), { headers: upstreamHeaders });
	console.info('[api/audio]', {
		target: parsed.toString(),
		hasRange: !!range,
		upstreamStatus: upstream.status,
		contentType: upstream.headers.get('content-type'),
		contentLength: upstream.headers.get('content-length'),
	});
	if (!upstream.ok && upstream.status !== 206) {
		throw error(safeStatus(upstream.status), `upstream ${upstream.status}`);
	}

	const headers = new Headers();
	headers.set('content-type', upstream.headers.get('content-type') ?? 'audio/mpeg');
	const cl = upstream.headers.get('content-length');
	if (cl) headers.set('content-length', cl);
	const cr = upstream.headers.get('content-range');
	if (cr) headers.set('content-range', cr);
	headers.set('accept-ranges', upstream.headers.get('accept-ranges') ?? 'bytes');
	headers.set('cache-control', 'public, max-age=86400');

	return new Response(upstream.body, { status: upstream.status, headers });
};
