#!/usr/bin/env python3
"""Freeze the DS-WER domain term lists, one per benchmark city.

DS-WER (`docs/reference/gsoc-proposal.md:100`, proposal Milestone 2) is Levenshtein
restricted to domain-critical words. This builds the term lists it scores against,
and it must run - and be committed - before any provider is scored, because a term
list edited after seeing a hypothesis is not a metric, it is a fit.

**Source.** OpenCouncil's public city registry, `GET /api/cities/{city}/people`. No
authentication, no transcript text, no provider hypothesis. The names of elected
members of a public council are public record; this file carries terms only.

**What is included.** The surnames of every person in the city's roster, and the
tokens of the city's own name and municipality name.

**What is excluded, and what that costs.** Community and settlement names ("Νέα
Κίος", "Ταλαμανάρα") and local acronyms are *not* included: no frozen public source
enumerates them, and inventing the list by reading transcripts is exactly the fit
this file exists to prevent. The error analysis found that names and *place names*
together carry 21.6% of our error tokens, so restricting the list to people and the
municipality makes DS-WER a **lower bound** on domain-term error, not an estimate of
it. That sentence belongs in any report that quotes the number.

**Aliases** are generated by fixed Greek suffix rules written into this script, never
by hand, so that no surface form can be added in response to a result. Each generated
form is enumerated explicitly in the output; there is no stemming at scoring time.

    python3 scripts/build_ds_wer_terms.py
"""
from __future__ import annotations

import json
import subprocess
import sys
import unicodedata
from pathlib import Path

ROOT = Path("/home/harold/opencouncil-fine-tuning")
sys.path.insert(0, str(ROOT))

from eval.controlled_eval.eval_freeze import ftoks  # noqa: E402

OUT = ROOT / "research/ds_wer/terms"
MANIFEST = ROOT / "research/eval-freeze-2026-08/manifest.json"
API = "https://opencouncil.gr/api"
RETRIEVED = "2026-08-11"
VERSION = 1

# An alias shorter than this (normalized) is dropped: short Greek surname stems
# collide with ordinary vocabulary, and a term list that matches ordinary words
# measures something other than domain accuracy.
MIN_ALIAS_LEN = 4


def get(url: str):
    """curl, not urllib: same reason as everywhere else in this repo."""
    r = subprocess.run(["curl", "-sSfL", "--retry", "2", url],
                       capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"{url}: {r.stderr[:300]}")
    return json.loads(r.stdout)


def inflect(surname: str) -> list[str]:
    """Nominative, genitive, accusative and vocative of a Greek surname.

    Fixed suffix rules, applied blind. Masculine -ος/-ας/-ης decline; the -ου and
    -α endings that Greek female surnames take are indeclinable and come back
    unchanged. Anything that matches no rule contributes its nominative only -
    a missed inflection costs recall on the metric, an invented one costs its
    validity, and only the first of those is recoverable later.
    """
    s = surname
    forms = {s}
    if s.endswith("ος"):
        stem = s[:-2]
        forms |= {stem + "ου", stem + "ο", stem + "ε"}
    elif s.endswith("ας"):
        forms.add(s[:-2] + "α")
    elif s.endswith("ης"):
        forms.add(s[:-2] + "η")
    elif s.endswith("ές"):
        forms.add(s[:-2] + "έ")
    elif s.endswith("ς"):
        forms.add(s[:-1])
    return sorted(forms)


def norm_key(text: str) -> str:
    """The scoring-time key: the frozen normalizer, joined. Empty if it tokenizes away."""
    return " ".join(ftoks(text))


def build_city(city: str, meetings: list[str]) -> dict:
    url = f"{API}/cities/{city}/people"
    people = get(url)
    city_rec = get(f"{API}/cities/{city}")

    # One term per distinct surname, not per person. Two roster entries sharing a
    # surname are the same domain word - councils really do seat relatives, and the
    # mayor of Argos appears twice in the registry. Treating that as an alias
    # collision would drop the single most-spoken name in the city.
    by_surname: dict[str, dict] = {}
    for p in people:
        name = (p.get("name") or "").strip()
        if not name:
            continue
        surname = name.split()[-1]
        key = norm_key(surname)
        rec = by_surname.setdefault(key, {
            "id": f"person:{key.replace(' ', '_')}", "canonical": surname,
            "klass": "person_surname", "covers": [], "aliases": inflect(surname)})
        rec["covers"].append(name)

    raw = sorted(by_surname.values(), key=lambda t: t["id"])

    for label, value in (("city_name", city_rec.get("name")),
                         ("municipality_name", city_rec.get("name_municipality"))):
        if value:
            raw.append({"id": f"place:{label}", "canonical": value,
                        "klass": "place_name", "covers": [value],
                        "aliases": [value]})

    # An alias may map to exactly one term id. Collisions are dropped from every
    # term that claims them, not silently assigned to whichever came first.
    seen: dict[str, set[str]] = {}
    for t in raw:
        for a in t["aliases"]:
            k = norm_key(a)
            if len(k.replace(" ", "")) >= MIN_ALIAS_LEN:
                seen.setdefault(k, set()).add(t["id"])
    collisions = {k for k, ids in seen.items() if len(ids) > 1}

    terms, dropped = [], []
    for t in raw:
        keys = []
        for a in t["aliases"]:
            k = norm_key(a)
            if len(k.replace(" ", "")) < MIN_ALIAS_LEN:
                dropped.append({"alias": a, "reason": "too_short", "term": t["id"]})
            elif k in collisions:
                dropped.append({"alias": a, "reason": "collision", "term": t["id"]})
            elif k not in keys:
                keys.append(k)
        if not keys:
            dropped.append({"alias": t["canonical"], "reason": "no_usable_alias",
                            "term": t["id"]})
            continue
        terms.append({"id": t["id"], "canonical": t["canonical"],
                      "klass": t["klass"], "covers": t["covers"], "aliases": keys})

    return {
        "city": city,
        "version": VERSION,
        "source": {"url": [url, f"{API}/cities/{city}"], "retrieved": RETRIEVED,
                   "note": "OpenCouncil public city registry. No transcript text, "
                           "no provider hypothesis."},
        "rule": {
            "included": ["surnames of every person in the city's OpenCouncil roster",
                         "the city name and the municipality name"],
            "excluded": ["community and settlement names", "local acronyms",
                         "generic civic vocabulary", "given names"],
            "excluded_because": "no frozen public source enumerates them; building "
                                "the list from transcripts would fit the metric to "
                                "the data it scores. DS-WER computed against this "
                                "list is a LOWER BOUND on domain-term error.",
            "aliases_from": "fixed Greek suffix rules in "
                            "scripts/build_ds_wer_terms.py::inflect - never hand-added",
            "alias_normalization": "aliases are stored already normalized by the "
                                   "frozen scorer (eval.controlled_eval.scoring.wtoks "
                                   "plus the frozen filler strip); the matcher uses "
                                   "that same normalizer. No stemming.",
            "min_alias_chars": MIN_ALIAS_LEN,
            "collision_rule": "one term per distinct surname (roster duplicates are "
                              "merged, not treated as a conflict); after that an "
                              "alias may map to exactly one term id, and aliases "
                              "claimed by more than one term are dropped from all "
                              "of them",
        },
        "meetings_in_scope": meetings,
        "terms": sorted(terms, key=lambda t: t["id"]),
        "dropped_aliases": sorted(dropped, key=lambda d: (d["reason"], d["term"])),
    }


def main() -> None:
    man = json.loads(MANIFEST.read_text())
    by_city: dict[str, list[str]] = {}
    for r in man["eval_windows"]:
        by_city.setdefault(r["city"], []).append(r["meeting_id"])

    OUT.mkdir(parents=True, exist_ok=True)
    for city, meetings in sorted(by_city.items()):
        rec = build_city(city, sorted(set(meetings)))
        p = OUT / f"{city}.json"
        p.write_text(json.dumps(rec, ensure_ascii=False, indent=1) + "\n")
        n_alias = sum(len(t["aliases"]) for t in rec["terms"])
        print(f"{city}: {len(rec['terms'])} terms, {n_alias} aliases, "
              f"{len(rec['dropped_aliases'])} dropped -> {p}")


if __name__ == "__main__":
    main()
